services:
  db:
    image: mysql:8.0
    container_name: haircut_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cucajay87
      MYSQL_DATABASE: haircut_app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: haircut_web
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Cucajay87
      DB_NAME: haircut_app

volumes:
  mysql_data: